#!/bin/bash
# Renders .env.production from Terraform outputs + the RAM access key
# Terraform generated, using .env.production.example as the template. Run
# this from infra/alibaba-cloud/terraform after `terraform apply`.
#
# Usage: ./render-env.sh > ../../../.env.production
set -euo pipefail

cd "$(dirname "$0")/../terraform"

: "${NEO4J_PASSWORD:?Set NEO4J_PASSWORD to the same value passed as TF_VAR_neo4j_password}"
KAFKA_BOOTSTRAP_SERVERS="${KAFKA_BOOTSTRAP_SERVERS:?Read this from the Alibaba Cloud console (see outputs.tf's alikafka_instance_id comment) and export it}"

tf_out() { terraform output -raw "$1"; }

cat <<ENV
# Generated by infra/alibaba-cloud/scripts/render-env.sh -- do not commit.
SYMPHONY_LLM=$([ -n "${DASHSCOPE_API_KEY:-}" ] && echo qwen || echo mock)
DASHSCOPE_API_KEY=${DASHSCOPE_API_KEY:-}

SYMPHONY_BUS=kafka
KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS}
KAFKA_TOPIC_EVENTS=symphony-events

SYMPHONY_BLACKBOARD=tablestore
TABLESTORE_ENDPOINT=$(tf_out tablestore_endpoint)
TABLESTORE_INSTANCE_NAME=$(tf_out tablestore_instance_name)
TABLESTORE_ACCESS_KEY_ID=$(tf_out ram_access_key_id)
TABLESTORE_ACCESS_KEY_SECRET=$(tf_out ram_access_key_secret)

NEO4J_URI=bolt://$(tf_out neo4j_ecs_public_ip):7687
NEO4J_USER=neo4j
NEO4J_PASSWORD=${NEO4J_PASSWORD}

SYMPHONY_API_CORS_ORIGINS=http://$(tf_out neo4j_ecs_public_ip):3000
NEXT_PUBLIC_API_URL=http://$(tf_out neo4j_ecs_public_ip):8000
ENV
